### ISSUE TITLE
issue when importing 

### ISSUE THREAD

**Issue by ilatic** [ab3lkaizen/SCEHUB#4]
### Motherboard model

MSI Z790-A PRO DDR4

### Version

Select one

### Command type

When using "import.bat"
![import](https://github.com/user-attachments/assets/c17c432f-b363-459b-8848-7e233de1eaca)

### Log file

![Capture](https://github.com/user-attachments/assets/8d3ba659-1850-461c-927a-edd27e2fbd1b)

**Comment by ab3lkaizen** [comment]
The error messages and their solutions are already documented in the README ([1](https://github.com/ab3lkaizen/SCEHUB?tab=readme-ov-file#warning-length-of-string-for-control-setup-question-not-updated-as-the-valuedefaults-specified-in-the-script-file-doesnt-reach-the-minimum-range-value) | [2](https://github.com/ab3lkaizen/SCEHUB?tab=readme-ov-file#system-configuration-not-modified)).
